### ISSUE TITLE
INFO

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#13]
issus un peu spéciale 

vous me connaissez et je suis directe et j'aime pas les quiproquos (car sa n’emmène que des problèmes, et je résous les problèmes pas dev pour rien ;-) ) alors je tiens à vous faire un roman pour que les choses soit claire sur notre manière de faire
si vous me connaissez, je vous connais également et vous avez du mal à extérioriser les choses, vous avez du mal à vous impliquer par crainte de tout peter le code ou les branch ou autres .... si si faite pas genre je sais que c'est le cas, .... ben maintenant c'est fini on est tous dev c'est terrifiant mais faut l’accepter

Je vais surtout parler pour les woopears
vraiment n'hésitez pas à créer des issus à créer des fichiers
des qu'ils y a une idée qui vous viens, partager la dans ce repos

j'attire votre attention la dessus car c'est très important, je pense que vous êtes comme moi et que vous faites pas tout cet investissement pour rien et donc si on veux vraiment que sa fonctionne et que l'on soit pas passif de notre avenir il faut alors être actif
(je dédicace cette belle phrase à tanguy)

donc manipuler des branch, créer des fichiers, cloner, pusher, puller, (j'ai fais du franglais pour les verbes désolé) faites des issus, ils faut absolument partager un max tout ce qui nous passe par la tête, il n'y a aucune mauvaise idée ou question tous est bon à prendre pour évoluer.

les documents que je crée, que vous créez etc ... on peux toujours améliorez les choses, donc on peux pas avoir un fichier dans ce repos sans qu'ils soient modifier par quelqu'un d'autre que sont créateur, on ne peux pas passer 15 jours sans avoir une issus qui apparaît ici (sauf si tout est déjà créé mais pour l'instant c'est pas le cas) ce n'est pas possible et si c'est le cas ils faut qu'on revois nos principes (je sais que vous allez le faire), mais voila je voulais vraiment faire le point la dessus

on est ensemble pas les uns contre les autres, les fichiers que je créer ne sont pas que pour moi, les fichiers que vous allez creer ne sont pas que pour vous, le partage est la clef de la réussite !

donc N'HESITEZ PAS

autre chose les fichiers dans ce repos sont créer en markdown donc c'est également quelque peut important de savoir manipuler un minimum le markdown, donc ce repos permet de s’entraîner à ce petit langage de mise en forme, MAIS PAS QUE, sa permet de vous entraîner aux branchs, au future fonctionnement de notre travail, vous pouvez par exemple

=> ouvrir une issus pour expliquer
=> creer une branch depuis develop
=> creer votre fonctionnalité (fichier)
=> push votre branch pour que les autres corrige
(tous sans oublier de mettre a jour votre issus pour dire au autre où en est votre travail)
=> on regardera la branch qui a été push on la valide
=> et ensuite le lead la mergera sur develop
=> quand develop est pret le lead merge sur master

ce repos + tous les fichier d'aide que l'on peux creer nous ferons progresser

répéter les taches permettront d’être bon dans notre domaine, je peux pas dire excellent le développement arrête pas d'évoluer on peut pas être parfait

et je vais finir sur le mot parfait ! PERSONNE n'est parfait ou connais tout ou est plus fort que l'autre, le dev n'est pas une discipline perso, c'est un sport d'équipe plus puissant que n'importe quel SPORT CO. car tout seul on s'éteins, dans le sport tout seul on fait du ping-pong on meurt pas. 
Dans le dev c'est une toute autre histoire.

bon apres mon magnifique roman rempli de fautes, j'ai mis une issus à david pour créer un fichier de doc avec les commandes pour utiliser vueCLI 
tanguy j'aimerais et je suis sur que toi aussi, que tu fasses un fichier sur le markdown pour qu'on est une base

pour ces deux fichier pas de soucis il existe déjà des truc tout fait sur github mais sa va vous faire pratique le markdown + participer et utiliser le système de branch.

voila les potos, je vous laisse 
@+

ps : si vous voulez en parler en priver ou tous ensemble pas de soucis (mais je suis sur que vous pensez la même chose que moi)
bien sur woopear passe après les priorités de chacun, on créer ceci pour un avenir
"avenir" veux bien dire ce que sa veux dire, c'est pas maintenant donc les priorités de chacun avant tout
et ensuite woopear avec tous les autres truc mdrrrr

**Comment by cecilems** [comment]
Pour le bien de ce projet, mieux vaut que je ne touche pas au code XD

**Comment by TanguyB17** [comment]
bien reçu, message concret, on aime ça.
Bienvenue à Cécile.
