### ISSUE TITLE
Tableau blanc et mode dessin

### ISSUE THREAD

**Issue by chaton** [woopear/welcome#15]
Bonsoir ou bonjour

Quel outil souhaitez vous utiliser pour brainstorming en commun ?

Pour moi deux plateforme de base qui permettent de dessiner
- google doc avec draw
-  miro

**Comment by j314h** [comment]
quand tu dis dessiner, tu pourrais en dire un peux plus ?
cela servirais seulement pendant les réunions ou est ce quelque chose pour faire de la conception ?

**Comment by cecilems** [comment]
je ne connais ni l'une ni l'autre, j'utiliserai donc celle qui vous va le mieux

**Comment by chaton** [comment]
Oui, je parle d'un outil de conception

permettant de définir l'architecture des services
de définir les passerelle d'un point de vue visuelle
mais aussi de pouvoir gribouiller pendant une reunion en distanciel

**Comment by j314h** [comment]
ok alors là on s'en remet à toi je pense
jamais rien utiliser de tel, à partager pour utiliser quelque chose de commun

**Comment by chaton** [comment]
voila un exemple de ce qu'il est possible de faire avec miro
https://miro.com/app/board/o9J_lQYJ_n4=/

dites moi ce que vous en pensez

**Comment by j314h** [comment]
donc pour moi c'est good j'adore, je vais ouvrir une instance pour woopear et pouvoir gerer plusieurs projet

**Comment by j314h** [comment]
les copains dites moi si c'est ok pour l'acces au miro de woopear
j'ai mis le lien d'invitation dans le salon rules-code

**Comment by David-Caignaert** [comment]
je suis aller dessu hier j'ai bien l'accés

**Comment by j314h** [comment]
ok d'acc je vois que tout le monde est membre du compte woopear 
je clos l'issus
