### ISSUE TITLE
Commit webhook discord

### ISSUE THREAD

**Issue by chaton** [woopear/welcome#16]
Grâce aux webhook de discord il est possible d'avoir un canal discord qui reçoit tous les commit (ou certain commit) directement depuis git

J'ai réussi a le faire sur gitlab mais jamais sur github

Il faut que le discord leader essaye

**Comment by j314h** [comment]
yes super idée je vais mettre ça en place aujourd'hui
merci pascal pour l'idée

**Comment by j314h** [comment]
par contre on parle de commit ou des issus ?
peut etre on peux faire les deux ....
dites moi si vous trouver que les deux serait pertinent
je vais deja faire les commits vu que pascal a deja fait je vais trouver des infos rapidement
et si les issus vous interesse aussi je chercherai pour les issus dans ce cas

**Comment by cecilems** [comment]
salut ! j'avais viré Discord de mon PC, vous êtes en train de dire qu'il faut que je le réinstalle c'est ça ?

**Comment by j314h** [comment]
si sa te dérange pas cecile, apres c'est surtout par rapport au commit et au avancement du projet 
qui seront envoyé directement sur discord pour tenir au courant tout le monde rapidement

**Comment by j314h** [comment]
en cours de creation

**Comment by j314h** [comment]
bot discord créer sa fonctionne super bien
j'ai fais les commit dans le salon rules-code dans discord 
comme ça quand il y a quoi que se soit sur ce repos 
on aura les notif dans le salon rules-code

confirmer que tout et ok et je clos

**Comment by David-Caignaert** [comment]
tout et ok pour moi.

**Comment by TanguyB17** [comment]
Good aussi de mon côté.

**Comment by chaton** [comment]
ca roule
