### ISSUE TITLE
Architecture SkillzMatcher

### ISSUE THREAD

**Issue by chaton** [woopear/welcome#18]
Un tableau pour tracer les grandes lignes

https://miro.com/welcomeonboard/rhSEtfhrX7pEtVNGZ1oIKk7cT9rlGxIu8nmcn5Oq7qx9qTcsqVissx6z2P4BVKsj

Ajoutez vos post-it afin que l'on vois le schéma général se dégager

**Comment by j314h** [comment]
ok faudra refaire une issus dans le repo skillzmatcher à ne pas oublier pascal ;-)

**Comment by j314h** [comment]
je clos celle ci aussi
