### ISSUE TITLE
Commande Marckdown (Markeup Language)

### ISSUE THREAD

**Issue by TanguyB17** [woopear/welcome#19]
Liste de commande d'utilisation de Marckdown.

**Comment by TanguyB17** [comment]
la documentation n'est pas finalisée.

**Comment by j314h** [comment]
tang sauf erreur de ma part, je crois il manque l'explication pour faire le retour à la ligne avec le double espace en fin de ligne
et si tu peux mettre un vrais exemple pour les liens genre un lien d'image ou autre

**Comment by TanguyB17** [comment]
ok je rectifie le dossier dans la journée.

**Comment by TanguyB17** [comment]
j'ai remis à jour la documentation Markdown, j'attend votre retour les amis.

**Comment by j314h** [comment]
pour moi nickel
david si tu vois quelque chose ?
sinon on clos et je merge

**Comment by David-Caignaert** [comment]
c'est bon pour moi
