### ISSUE TITLE
initialisation du fonctionnement des fichier d'environnement

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#20]
Je vais faire une petite doc sur les .env et les .env.local
pour vous expliquez comment cela fonctionne et comment on va s'organiser

**Comment by David-Caignaert** [comment]
oui ca j'ai jamais utilisé et je n'ai pas trop compris

**Comment by j314h** [comment]
ok alors quand j'aurais fini la doc on ce fera un petit call en plus pour pratiquer

**Comment by David-Caignaert** [comment]
ca roule

**Comment by TanguyB17** [comment]
pleinement d'accord avec vous, call obligatoire. Merci.

**Comment by chaton** [comment]
comme pour le CLI je ne vois pas le doc
pouvez vous mettre le fichier en lien dans les dépendance quand vous le cité ?
Merci ;-)

**Comment by j314h** [comment]
commande terminé 
https://github.com/woopear/welcome/blob/7d91c7ae575202312575e4e33c6c9dfa2af966ea/rules/files-.env.md
