### ISSUE TITLE
doc commande linux basic

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#23]
creer une doc sur les commandes linux basic

**Comment by David-Caignaert** [comment]
cool mci

**Comment by j314h** [comment]
ail ail beau gosse le bibouche mdrrrrrrrrr

**Comment by David-Caignaert** [comment]
t' as vu j'ai changé depuis le confinement lol

**Comment by TanguyB17** [comment]
encore un barbu, c'est le retour de la guerre de 14- 18

**Comment by David-Caignaert** [comment]
document termier à valider.

**Comment by j314h** [comment]
pour moi c'est ok

**Comment by TanguyB17** [comment]
Tout bon, c clair pour moi.
