### ISSUE TITLE
doc commande git basic

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#24]
creer une doc sur les commandes git basic

**Comment by TanguyB17** [comment]
ok, prévu ce week-end sans problème

**Comment by TanguyB17** [comment]
le fichier commande Git Basic est terminé, à vérifier.

**Comment by chaton** [comment]
Bonjour,
@TanguyB17 , je ne vois pas le fichier
peux tu me dire ou il se trouve ?
Merci

**Comment by j314h** [comment]
https://github.com/woopear/welcome/blob/960b21f2417de25d816238e4fadce114b614fb00/rules/commandGit.md

**Comment by David-Caignaert** [comment]
slt pascal il faut que tu vas sur ca branche commandeGit pour le voir

**Comment by chaton** [comment]
Merci, 
oui, j'ai oublié d'aller checker les branches.
merci pour le lien ;-)

**Comment by chaton** [comment]
ok pour moi
j'avoue que je prefere utiliser gitKraken
mais j'avoue également pour les commande a peine complexe
il est bon de passer par la ligne de commande afin d'être sur de ce que l'on fait

**Comment by j314h** [comment]
oui pour le permalink désoler j'ai oublier de montrer comment on faisait et du coup tanguy ou david ne peuvent pas le faire
merci @chaton pour le retour

**Comment by j314h** [comment]
pour moi c'est ok j'ai apporter quelques modif
@David-Caignaert si tout est ok pour toi ferme l'issus

**Comment by David-Caignaert** [comment]
c'est ok pour moi je ferme
