### ISSUE TITLE
environnement de travail woopear

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#26]
liste et présentation de l'environnement que nous devons tous avoir 
pour travailler dans de bonne condition
travail de groupe sur le meme fichier sa permettra de travailler en synchro

les differents points (n'hésitez pas à rajouter si il y en a d'autre)

- tanguy 
=> os
=> outils de l'os
=> package indispensable

- david
=> environement de travaille (vscode, des liens de google (figma etc ...), etc ...)
=> pluging de l'ide

- john
=> config de l'ide

bien sur j'ai pas grand chose à faire mais c'est normalement je connais pas les parties d'avant XD

comme d'hab on a le temps
je répete le but est de travailler en synchro car on sera sur le meme fichier

par contre je vous explique
on travail sur le meme fichier mais pas sur la meme branch
je vais creer un fichier sur la branch develop (faudra attendre que je le fasse avant de commencer)
et ensuite chacun sur son poste on creera une branch et chacun fera sa popote et comme d'habitude quand on a fini 
chacun push sa branch pour que ensuite je puisse merge sur develop

à demain les potos

**Comment by TanguyB17** [comment]
Ok bien reçu, a demain.

**Comment by j314h** [comment]
le fichier est creer sur develop donc à nous de jouer ;-)
