### ISSUE TITLE
fichier commande vue CLI

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#3]
creer un fichier markdown pour mettre les differente commande pour installer vue CLI et comment utiliser vue CLI
pour un projet vuejs 3 + typescript + sass

faire plusieurs exemple

**Comment by David-Caignaert** [comment]
documentation pour la création d'un projet vuejs3/CLI terminer

**Comment by j314h** [comment]
alors sauf erreur de ma part mon gros
dans ta branch que tu as faite je vois pas de document creer

**Comment by chaton** [comment]
Je ne vois pas ce document 
ou l'avez vous posé

je pense qu'il faut ajouter des lien vers les fichiers quand on les mentionne afin de faciliter la navigation

**Comment by j314h** [comment]
yes tres bonne idée

**Comment by j314h** [comment]
mais comme les issus vont etre close tu crois que c'est pertinant ?

**Comment by chaton** [comment]
je ne pense que cela pause probleme
lorsque l'on evoque un fichier on le met en dépendance simplement avec 
un lien donc cela ne pose pas de probleme de réplication et ou de maintenance je pense

en fait je viens de constater qu'il ne permet de mettre des lien naturellement vers les fichier présent dans le repos

je cherche comment faire et je reviens

**Comment by chaton** [comment]
Bon le bouton référence de zenhub ne permet pas de désigner des fichier ou des commit 
mais uniquement des PULL ou des issue

je continue a chercher

**Comment by chaton** [comment]
J'ai fait un "copy permalink" depuis le repo git pour produire cela
C'est pas idéal

https://github.com/woopear/welcome/blob/bcb32ec46f78ad387d5ddf5afb3a60ff1bad5ffe/rules/vuejs3-CLI-instalation.md

**Comment by David-Caignaert** [comment]
push du fichier final fait plus qu'à valider par tlm et à merger

**Comment by j314h** [comment]
je pense @chaton que nous pouvons directement lier les commits qui sont en rapport avec l'issus mais je ne trouve pas encore comment faire ça automatiquement

**Comment by j314h** [comment]
effectivement avec la pullrequest j'ai l'impression que c'est redondant 
la derniere solution de pascal et la mieux

**Comment by j314h** [comment]
ou alors le link en directe mais bon il sera plus valable une fois la branch merger et supprimé
[](https://github.com/woopear/welcome/blob/vueCliDoc/rules/vuejs3-CLI-instalation.md)

**Comment by j314h** [comment]
[vueCli](https://github.com/woopear/welcome/blob/vueCliDoc/rules/vuejs3-CLI-instalation.md)

**Comment by j314h** [comment]
pour moi le document est ok j'ai corriger ce que j'ai pu voir comme erreur
@TanguyB17 si tu vois un truc n'hesite pas si c'est ok clos l'issus et je mergerai

on fera un call pour parler de l'install également @TanguyB17

**Comment by chaton** [comment]
En fait le lien que j'ai posé au dessus est un permalien de github
a mon avis il désigne le fichier tout a long de sa vie
et ne tiens pas compte de la branche ou autre

a vérifier

**Comment by j314h** [comment]
oui oui c'est exactement ça @chaton c'est pour ça que c'est la mieux solution ;-)
c'est cette solution qu'il faudra utiliser
