### ISSUE TITLE
faire fichier sur branch git

### ISSUE THREAD

**Issue by j314h** [woopear/welcome#9]
creer fichier mardown pour fonctionnement des branch develop relase feature etc ....

**Comment by j314h** [comment]
j'ai donc fini de creer les fichier pour les regles des branch
sa pas été évident car il faut que tout le monde comprenne
merci de faire un retour dans cette issus pour savoir si sa vous conviens ou pas
si jamais sa vous conviens pas faite les modifications des fichiers vous même se sera toujours 
mieux que si c'est moi qui fait les modifications (on a chacun sa façon de communiqué les choses et la mienne ne conviens peut etre pas)

**Comment by j314h** [comment]
je passe cette issus en review, si c'est ok pour vous commenter et fermer l'issus

@+

**Comment by chaton** [comment]
C’est OK pour moi pour gitflow

Il va falloir que je me dérouiller un peu j’ai pris des mauvaise habitude en développant beaucoup seul ;-)

John tu es le gitleader ? N'est ce pas ?

**Comment by chaton** [comment]
Heu question. Si je clos
Ca clos pour tous
Donc je pense qu'il faut un consensus de fermeture

C’est clos pour moi

**Comment by j314h** [comment]
pascal je sais pas ce que tu en penses mais le consensus
se serait quand chaque personne assigné pense que l'issus est ok ?

pour le git leader, je ne sais pas on en parlera quand on sera tous ensemble

ensuite pour gitflow t'inquiete pas on va pas l'appliquer maintenant
enfin en tous cas pas les commandes

on va continuer d'utiliser les commandes de base pour le moment, pour s'habitué au fonctionnement des branchs
et quand on ce sentira bien on ajoutera gitflow dans nos commandes, pour y aller en douceur je pense que c'est le mieux

**Comment by TanguyB17** [comment]
dossier étudié, je reviens vers vous pour les points encore flou mais avec la pratique, il paraît qu'on s'améliore jusqu'à devenir une bête de code.
issue clos pour moi.

**Comment by David-Caignaert** [comment]
C'est ok aussi pour moi.
issue clos pour moi aussi.
